CREATE INDEX val ON pagos(valor);
CREATE INDEX cliente_id ON pagos (cliente_id);
CREATE INDEX fechas ON promociones(fecha_fin, fecha_inicio);
CREATE INDEX dcto ON promociones(DESCUENTO);
CREATE INDEX promo_id ON clientes(promo_id);
CREATE INDEX promo_ciudad ON promo_ciudad(promo_id, ciudad_id);
CREATE INDEX promo_act ON promo_actividad(promo_id, actividad_id);
CREATE INDEX promo_plan ON promo_plan(promo_id, plan_id);
CREATE INDEX promo_cal ON promo_calificacion(promo_id, calificacion_id);
CREATE INDEX calificacion ON calificacion(id, nombre);
CREATE INDEX ciudad ON ciudades(id, nombre);
CREATE INDEX plan ON plan_comercial(id, nombre);
CREATE INDEX actividad ON actividad_eco(id, nombre);
CREATE INDEX estado ON promociones(estado);
CREATE INDEX fecha_inicio ON promociones(fecha_inicio);
CREATE INDEX fecha_fin ON promociones(fecha_fin);
CREATE INDEX prod_cliente_id ON prod_cliente(cliente_id);
CREATE INDEX info_registro ON registro_asignaciones(promo_id, cliente_id, fecha);
CREATE INDEX nombre_act ON actividad_eco(nombre);
CREATE INDEX nombre_cal ON calificacion(nombre);
CREATE INDEX nombre_ciud ON ciudades(nombre);
CREATE INDEX nombre_plan ON plan_comercial(nombre);