ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_CIUDAD FOREIGN KEY (ciudad_id) REFERENCES CIUDADES(id);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_PLAN FOREIGN KEY (plan_id) REFERENCES PLAN_COMERCIAL(id);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_ACTIVIDAD FOREIGN KEY (actividad_id) REFERENCES ACTIVIDAD_ECO(id);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_CALIFICACION FOREIGN KEY (calificacion_id) REFERENCES CALIFICACION(id);
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_PROMO FOREIGN KEY (promo_id) REFERENCES PROMOCIONES(id);
