ALTER TABLE PROMO_CIUDAD ADD CONSTRAINT FK_CIUDAD_PROMO FOREIGN KEY (promo_id) REFERENCES PROMOCIONES(id);
ALTER TABLE PROMO_CIUDAD ADD CONSTRAINT FK_PROMO_CIUDAD FOREIGN KEY (ciudad_id) REFERENCES CIUDADES(id);
