ALTER TABLE PROMO_ACTIVIDAD ADD CONSTRAINT FK_ACTIVIDAD_PROMO FOREIGN KEY (promo_id) REFERENCES PROMOCIONES(id);
ALTER TABLE PROMO_ACTIVIDAD ADD CONSTRAINT FK_PROMO_ACTIVIDAD FOREIGN KEY (actividad_id) REFERENCES ACTIVIDAD_ECO(id);
