ALTER TABLE PROMO_CALIFICACION ADD CONSTRAINT FK_CALIFICACION_PROMO FOREIGN KEY (promo_id) REFERENCES PROMOCIONES(id);
ALTER TABLE PROMO_CALIFICACION ADD CONSTRAINT FK_PROMO_CALIFICACION FOREIGN KEY (calificacion_id) REFERENCES CALIFICACION(id);
