ALTER TABLE PROMO_PLAN ADD CONSTRAINT FK_PLAN_PROMO FOREIGN KEY (promo_id) REFERENCES PROMOCIONES(id);
ALTER TABLE PROMO_PLAN ADD CONSTRAINT FK_PROMO_PLAN FOREIGN KEY (plan_id) REFERENCES PLAN_COMERCIAL(id);
